version: "3.4"
services:
  backend:
    depends_on:
      - mysql
      - redis
    image: weekend-contest-smv-be:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DSN=root:bW90aGVyIGZ1Y2tlciBub29i@tcp(mysql:3306)/user_tracking?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local
      - REDIS_URL=redis://redis:6379/1
    restart: always
  frontend:
    depends_on:
      - backend
      - mysql
      - redis
    image: weekend-contest-smv-fe:v1.0.0
    ports:
      - "80:80"
    environment:
      - REACT_APP_SERVER_URL=http://backend:8080
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql-cm
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bW90aGVyIGZ1Y2tlciBub29i
      MYSQL_DATABASE: user_tracking
      MYSQL_USER: user1
      MYSQL_PASSWORD: 1
  redis:
    image: redis:6
volumes:
  db_data:
    name: user_tracking
    external: true